---
nvm_repo: "git://github.com/creationix/nvm.git"
# This could be set to 'user' to support user installs.
nvm_env: user

nvm_version: v0.32.1

# This sets the nvm global nodejs version.| stable:最新, lts/boron:6.9.1, lts/argon:4.6.2 
nvm_default_node_version: lts/boron

# List of nodejs versions to install.
nvm_node_versions:
  - lts/boron

# List of default packages to install on each nodejs version.
nvm_global_packages: []

# List of users to install nvm and nodejs versions to.
# Ignored if nvm_env is set to 'system'
nvm_users: [vagrant]

nvm_root: "/home/vagrant/.nvm"